---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/sa.scc.mcs: s0:c11,c5
    openshift.io/sa.scc.supplemental-groups: 1000120000/10000
    openshift.io/sa.scc.uid-range: 1000120000/10000
  creationTimestamp: "2021-08-03T09:14:02Z"
  labels:
    kubernetes.io/metadata.name: kube-system
  name: kube-system
  resourceVersion: "658"
  uid: 93c62bd8-ce64-47b0-a737-2236a9be1484
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
