---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-08-03T09:19:00Z"
  generateName: etcd-quorum-guard-85b4c88c96-
  labels:
    k8s-app: etcd-quorum-guard
    name: etcd-quorum-guard
    pod-template-hash: 85b4c88c96
  name: etcd-quorum-guard-85b4c88c96-nmk5g
  namespace: openshift-etcd
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: etcd-quorum-guard-85b4c88c96
    uid: bc790f92-7b51-4471-9530-f80a1da13be2
  resourceVersion: "22014"
  uid: dd4bff0c-8159-401f-ab31-7272973fedeb
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: k8s-app
            operator: In
            values:
            - etcd-quorum-guard
        topologyKey: kubernetes.io/hostname
  containers:
  - args:
    - -c
    - |
      # properly handle TERM and exit as soon as it is signaled
      set -euo pipefail
      trap 'jobs -p | xargs -r kill; exit 0' TERM
      sleep infinity & wait
    command:
    - /bin/bash
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:c7210ebe8b9c7b0799b4188be59bb712e50e1e26a28e0dfa4c7b6f4e9745a1c7
    imagePullPolicy: IfNotPresent
    name: guard
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - |
          declare -r health_endpoint="https://localhost:2379/health"
          declare -r cert="/var/run/secrets/etcd-client/tls.crt"
          declare -r key="/var/run/secrets/etcd-client/tls.key"
          declare -r cacert="/var/run/configmaps/etcd-ca/ca-bundle.crt"
          export NSS_SDB_USE_CACHE=no
          [[ -z $cert || -z $key ]] && exit 1
          curl --max-time 2 --silent --cert "${cert//:/\:}" --key "$key" --cacert "$cacert" "$health_endpoint" |grep '{ *"health" *: *"true" *}'
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      requests:
        cpu: 10m
        memory: 5Mi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /var/run/secrets/etcd-client
      name: etcd-client
    - mountPath: /var/run/configmaps/etcd-ca
      name: etcd-ca
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-6vzq9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: ip-x-ipv4-000004-x.ec2.internal
  nodeSelector:
    node-role.kubernetes.io/master: ""
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 3
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/etcd
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: etcd-client
    secret:
      defaultMode: 420
      secretName: etcd-client
  - configMap:
      defaultMode: 420
      name: etcd-ca-bundle
    name: etcd-ca
  - name: kube-api-access-6vzq9
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-08-03T09:21:35Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-08-03T09:28:20Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-08-03T09:28:20Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-08-03T09:21:35Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://8bf9e4c25f16c94b76e909945be90d5e3bab88a0cde1d835ed9511b85c252035
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:c7210ebe8b9c7b0799b4188be59bb712e50e1e26a28e0dfa4c7b6f4e9745a1c7
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:c7210ebe8b9c7b0799b4188be59bb712e50e1e26a28e0dfa4c7b6f4e9745a1c7
    lastState: {}
    name: guard
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-08-03T09:21:37Z"
  hostIP: x-ipv4-000005-x
  phase: Running
  podIP: x-ipv4-000005-x
  podIPs:
  - ip: x-ipv4-000005-x
  qosClass: Burstable
  startTime: "2021-08-03T09:21:35Z"
