---
apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2021-08-03T09:19:32Z"
    labels:
      app.kubernetes.io/managed-by: prometheus-operator
      app.kubernetes.io/name: kubelet
      k8s-app: kubelet
    name: kubelet
    namespace: kube-system
    resourceVersion: "22168"
    uid: c4b2bee4-6ac1-499f-b4dc-156464a7480a
  subsets:
  - addresses:
    - ip: x-ipv4-000007-x
      targetRef:
        kind: Node
        name: ip-x-ipv4-000008-x.ec2.internal
        uid: f021198e-17c0-424c-b8c2-f83a95c39406
    - ip: x-ipv4-000009-x
      targetRef:
        kind: Node
        name: ip-x-ipv4-000010-x.ec2.internal
        uid: b26454dd-8a75-49df-8b67-9966fc9dd2f2
    - ip: x-ipv4-000002-x
      targetRef:
        kind: Node
        name: ip-x-ipv4-000001-x.ec2.internal
        uid: 49e3273a-f45c-4bbb-82a6-e8b1174be2ba
    - ip: x-ipv4-000005-x
      targetRef:
        kind: Node
        name: ip-x-ipv4-000004-x.ec2.internal
        uid: 1a3209c9-244b-4f76-8b75-2dc127842c00
    - ip: x-ipv4-000003-x
      targetRef:
        kind: Node
        name: ip-x-ipv4-000006-x.ec2.internal
        uid: 7ee95448-ed90-4fc5-ad90-97d777a49821
    - ip: x-ipv4-000011-x
      targetRef:
        kind: Node
        name: ip-x-ipv4-000012-x.ec2.internal
        uid: e84f9dd7-6e8f-463f-b321-cb8cec438f2d
    ports:
    - name: https-metrics
      port: 10250
      protocol: TCP
    - name: http-metrics
      port: 10255
      protocol: TCP
    - name: cadvisor
      port: 4194
      protocol: TCP
kind: EndpointsList
metadata:
  resourceVersion: "41799"
