---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.129.0.12"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.129.0.12"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2021-08-03T09:21:27Z"
  labels:
    app: installer
  name: installer-2-ip-10-0-187-218.ec2.internal
  namespace: openshift-etcd
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: revision-status-2
    uid: eb00b54f-21f5-44eb-8c31-3e035017b095
  resourceVersion: "12690"
  uid: a11c20b4-9c46-4fbb-96b8-074ca0d2ec46
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - -v=2
    - --revision=2
    - --namespace=openshift-etcd
    - --pod=etcd-pod
    - --resource-dir=/etc/kubernetes/static-pod-resources
    - --pod-manifest-dir=/etc/kubernetes/manifests
    - --configmaps=etcd-pod
    - --configmaps=etcd-serving-ca
    - --configmaps=etcd-peer-client-ca
    - --configmaps=etcd-metrics-proxy-serving-ca
    - --configmaps=etcd-metrics-proxy-client-ca
    - --secrets=etcd-all-certs
    - --cert-dir=/etc/kubernetes/static-pod-resources/etcd-certs
    - --cert-configmaps=restore-etcd-pod
    - --cert-configmaps=etcd-scripts
    - --cert-configmaps=etcd-serving-ca
    - --cert-configmaps=etcd-peer-client-ca
    - --cert-configmaps=etcd-metrics-proxy-serving-ca
    - --cert-configmaps=etcd-metrics-proxy-client-ca
    - --cert-secrets=etcd-all-certs
    command:
    - cluster-etcd-operator
    - installer
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:272b194c6889337ce2315fa4da7c2f033203fe33f2753025813f6a49b318c8f9
    imagePullPolicy: IfNotPresent
    name: installer
    resources:
      limits:
        cpu: 150m
        memory: 200M
      requests:
        cpu: 150m
        memory: 200M
    securityContext:
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: kubelet-dir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-0-187-218.ec2.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    runAsUser: 0
  serviceAccount: installer-sa
  serviceAccountName: installer-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes/
      type: ""
    name: kubelet-dir
  - name: kube-api-access
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3600
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-08-03T09:21:27Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-08-03T09:21:43Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-08-03T09:21:43Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-08-03T09:21:27Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://c7f214d62dee0efde5b80be6e9be79649bb9c223ee93e920dda64b2cfb9ab107
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:272b194c6889337ce2315fa4da7c2f033203fe33f2753025813f6a49b318c8f9
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:272b194c6889337ce2315fa4da7c2f033203fe33f2753025813f6a49b318c8f9
    lastState: {}
    name: installer
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://c7f214d62dee0efde5b80be6e9be79649bb9c223ee93e920dda64b2cfb9ab107
        exitCode: 0
        finishedAt: "2021-08-03T09:21:42Z"
        reason: Completed
        startedAt: "2021-08-03T09:21:40Z"
  hostIP: 10.0.187.218
  phase: Succeeded
  podIP: 10.129.0.12
  podIPs:
  - ip: 10.129.0.12
  qosClass: Guaranteed
  startTime: "2021-08-03T09:21:27Z"
